### ISSUE TITLE
Error when running mvn proxy-dependency:resolve -Ptest

### ISSUE THREAD

**Issue by dzuluaga** [apigee/proxy-dependency-maven-plugin#19]
hey guys,

I'm trying to run the plugin and the goal without executing the entire Maven lifecycle. The purpose is to be able to leverage the tool of our preference through plugins. Here's the command that I'm trying to run `mvn proxy-dependency:resolve -Ptest`. Any clue what might be wrong?

Here's the error log from Maven.
http://tny.cz/d2e96de7

This is was ran it from [here](https://github.com/apigee/proxy-dependency-maven-plugin/tree/master/samples/api-bundles-recommended/src/gateway/forecastweatherapi).

Thanks!

**Comment by sriki77** [comment]
This might be a network issue or an issue in settings.xml of maven.

**Comment by dzuluaga** [comment]
Thanks Srikanth. Running `mvn install -Ptest -Dusername=$ae_username -Dpassword=$ae_password` did the trick.

**Comment by dzuluaga** [comment]
This can be closed. Workaround found.
