### ISSUE TITLE
Support for non-JS resources

### ISSUE THREAD

**Issue by sriki77** [apigee/proxy-dependency-maven-plugin#2]
<a href="https://github.com/sriki77"><img src="https://avatars.githubusercontent.com/u/127582?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sriki77](https://github.com/sriki77)**
_Tuesday Mar 18, 2014 at 16:09 GMT_
_Originally opened as https://github.com/apigeecs/proxy-dependency-maven-plugin/issues/1_

---

Only Javascript resources are supported for copying by proxy replacer plugin. Support for non-JS resources should be added.

**Comment by Priyanky** [comment]
Fixed for py , java , xsl and node
